Repository krafs/LevelUp, pull requests merged in 2022-10, with the labels that each got.

#93 fix: Reimplement Widgets.ButtonText
  Source/Actions/AnimationAction.cs
  Source/Actions/SoundAction.cs
  Source/CustomWidgets.cs
Labels: bug

#95 German translation change: Fähigkeit -> Fertigkeit
  Languages/German/Keyed/German.xml
Labels: translation

#97 build: Add dependabot bumping of RimRef
  .github/dependabot.yml
Labels: build

#94 feat: Add support for 1.4
  About/About.xml
  README.md
Labels: feature

#99 Add StaticConstructorOnStartup for CustomWidgets
  Source/CustomWidgets.cs
Labels: feature

#100 Make sure Settings are initialized on startup
  Source/Patcher.cs
Labels: bug

#101 Use FleckMaker to create Flecks
  Source/Actions/FleckAnimation.cs
Labels: bug

#103 Use SkillRecord.Level instead of SkillRecord.levelInt.
  LevelUp.csproj
  Source/Actions/TextAction.cs
  Source/GenLevelingInfo.cs
Labels: bug

#107 Adds the Italian language
  Languages/Italian/Deflnjected/FleckDefs/FleckDefs.xml
  Languages/Italian/Deflnjected/LevelUp.ActionDefs/LevelUp.ActionDefs.xml
  Languages/Italian/Deflnjected/SoundDefs/SoundDefs.xml
  Languages/Italian/Keyed/Italian.xml
Labels: translation
